spring.datasource.url=jdbc:mysql://localhost:3306/teambuilder
spring.datasource.username=root
spring.datasource.password=N@hdus456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=8Kf4mP2xQ9vL7nR5tY1zW3cD6hJ8sA0bX5eN2kM9pL4qT7uV
jwt.expiration=86400000